### ISSUE TITLE
Error when building multithreaded maven project 

### ISSUE THREAD

**Issue by cbraun1980** [crowdcode-de/KissMDA#48]
If you have multiple modules with kissMDA and you build the maven project with -T option (multi threaded), you will get the following exception sometimes.

[ERROR] Failed to execute goal de.crowdcode.kissmda.maven:kissmda-maven-plugin:2.0.0:generate (default) on project entsorgerportal-abrechnung-domain-model: Execution default of goal de.crowdcode.kissmda.maven:kissmda-maven-plugin:2.0.0:generate failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.crowdcode.kissmda.maven:kissmda-maven-plugin:2.0.0:generate (default) on project entsorgerportal-abrechnung-domain-model: Execution default of goal de.crowdcode.kissmda.maven:kissmda-maven-plugin:2.0.0:generate failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal de.crowdcode.kissmda.maven:kissmda-maven-plugin:2.0.0:generate failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 11 more
Caused by: java.lang.NullPointerException
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:364)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getPackageForURI(XMLHandler.java:2515)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.getFactoryForPrefix(XMLHandler.java:2422)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createObjectByType(XMLHandler.java:1299)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.createTopObject(XMLHandler.java:1468)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1019)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:87)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1001)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:712)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:169)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:181)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:180)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1494)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1282)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:255)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:270)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:397)
	at de.crowdcode.kissmda.core.uml.ReaderWriter.load(ReaderWriter.java:127)
	at de.crowdcode.kissmda.core.uml.PackageHelper.getRootPackage(PackageHelper.java:69)
	at de.crowdcode.kissmda.cartridges.simplejava.SimpleJavaTransformer.getRootPackage(SimpleJavaTransformer.java:224)
	at de.crowdcode.kissmda.cartridges.simplejava.SimpleJavaTransformer.transform(SimpleJavaTransformer.java:116)
	at de.crowdcode.kissmda.maven.plugin.KissMdaMojo.useTransformerNamesWithOrder(KissMdaMojo.java:268)
	at de.crowdcode.kissmda.maven.plugin.KissMdaMojo.execute(KissMdaMojo.java:183)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 12 more

**Comment by lofidewanto** [comment]
I'm trying this with 2.1.0-SNAPSHOT version:

`clean package -T 4` in the project: KissMDA/app-examples/kissmda-app-test

and I get:

[INFO] Using the MultiThreadedBuilder implementation with a thread count of 4
...
[INFO] --- maven-jar-plugin:2.6:test-jar (default) @ kissmda-app-test ---
[INFO] Building jar: /Users/lofidewanto/git/KissMDA/app-examples/kissmda-app-test/target/kissmda-app-test-2.1.0-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.704 s (Wall Clock)
[INFO] Finished at: 2017-08-22T22:39:22+02:00
[INFO] Final Memory: 35M/374M
[INFO] ------------------------------------------------------------------------

**Comment by lofidewanto** [comment]
Through this exception: 

`at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:397)
at de.crowdcode.kissmda.core.uml.ReaderWriter.load(ReaderWriter.java:127)`

I found this static variable: 

`protected static final ResourceSet resourceSet = new ResourceSetImpl();`

I changed this to non-static.

Please test the version 2.1.0-SNAPSHOT
